### ISSUE TITLE
Prevents startup! KeyError: 'errorDescription'

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/aioupnp#11]
```2019-04-28 17:12:02,264 INFO     lbrynet.extras.daemon.Components:499: found upnp gateway: INTELBRAS WRN 300
2019-04-28 17:12:02,280 INFO     lbrynet.extras.daemon.Components:510: got external ip from UPnP: 192.168.1.2
2019-04-28 17:12:02,281 INFO     lbrynet.extras.daemon.Components:524: add UPnP port mappings
2019-04-28 17:12:02,318 ERROR    lbrynet.extras.daemon.Component:61: Error setting up upnp
Traceback (most recent call last):
  File "lbrynet\extras\daemon\Component.py", line 55, in _setup
  File "lbrynet\extras\daemon\Components.py", line 570, in start
  File "lbrynet\extras\daemon\Components.py", line 530, in _maintain_redirects
  File "lbrynet\extras\daemon\Components.py", line 50, in gather_dict
  File "lbrynet\extras\daemon\Components.py", line 48, in wait_value
  File "site-packages\aioupnp\upnp.py", line 167, in get_next_mapping
  File "site-packages\aioupnp\upnp.py", line 109, in _get_port_mapping_by_index
  File "site-packages\aioupnp\commands.py", line 47, in __call__
  File "site-packages\aioupnp\protocols\scpd.py", line 141, in scpd_post
  File "site-packages\aioupnp\serialization\soap.py", line 54, in deserialize_soap_post_response
  File "site-packages\aioupnp\fault.py", line 12, in handle_fault
KeyError: 'errorDescription'
2019-04-28 17:12:02,393 INFO     torba.client.basenetwork:88: ```

**Comment by tzarebczan** [comment]
This prevents startup without the use_upnp: false setting

**Comment by tzarebczan** [comment]
Related https://github.com/lbryio/lbry/issues/1917

**Comment by tzarebczan** [comment]
@jackrobison do you know if this would be fixed by your latest changes? I had 2 users run into it recently.
