### ISSUE TITLE
3 UPNP issues spotted recently

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/aioupnp#2]
These pile up on the logs since it re-requests upnp. 

1) ```2019-01-02 17:37:14,227 ERROR    aioupnp.protocols.ssdp:81: failed to decode SSDP packet from 192.168.0.1:1900 (missing required field usn): b'485454502f312e3120323030204f4b0d0a53543a75726e3a64736c666f72756d2d6f72673a736572766963653a4d616e6167656d656e745365727665723a310d0a4558543a0d0a5345525645523a20437573746f6d2f312e302055506e502f312e302050726f632f5665720d0a55534e3a757569643a757569643a66333033386532342d663034652d313165382d383733302d3130356630363333626365300a3a3a75726e3a64736c666f72756d2d6f72673a736572766963653a4d616e6167656d656e745365727665723a310d0a43414348452d434f4e54524f4c3a6d61782d6167653d313230393630300d0a4c4f434154494f4e3a20687474703a2f2f3139322e3136382e302e313a34393433312f646576696365646573632e786d6c0d0a0d0a'```

2) 
```2018-12-23 02:11:03,665 ERROR    asyncio:1597: Task exception was never retrieved
future: <Task finished coro=<Gateway._discover_gateway() done, defined at site-packages\aioupnp\gateway.py:157> exception=UnicodeDecodeError('utf-8', b'<?xml version="1.0"?>\r\n<root xmlns="urn:schemas-upnp-org:device-1-0"><specVersion><major>1</major><minor>0</minor></specVersion><device><deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType><friendlyName>ARRIS TG2492LG-85 Router</friendlyName><manufacturer>ARRIS</manufacturer><manufacturerURL>http://www.arrisi.com/</manufacturerURL><modelDescription>ARRIS TG2492LG-85 Router</modelDescription><modelName>ARRIS TG2492LG-85 Router</modelName><modelNumber>\xf0_\xf0</modelNumber><modelURL>http://www.arrisi.com/</modelURL><serialNumber>AA1P80581207</serialNumber><UDN>uuid:30353831-3230-3700-0000-48d34396e685</UDN><serviceList><service><serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType><serviceId>urn:upnp-org:serviceId:Layer3Forwarding1</serviceId><controlURL>/ctl/L3F</controlURL><eventSubURL>/evt/L3F</eventSubURL><SCPDURL>/L3F.xml</SCPDURL></service></serviceList><deviceList><device><deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType><friendlyName>WANDevice</friendlyName><manufacturer>ARRIS</manufacturer><manufacturerURL>http://www.arrisi.com/</manufacturerURL><modelDescription>WANDevice</modelDescription><modelName>WANDevice</modelName><modelNumber>20180122</modelNumber><modelURL>http://www.arrisi.com/</modelURL><serialNumber>AA1P80581207</serialNumber><UDN>uuid:30353831-3230-3700-0000-48d34396e685</UDN><UPC>TG2492LG-85</UPC><serviceList><service><serviceType>urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1</serviceType><serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId><controlURL>/ctl/CmnIfCfg</controlURL><eventSubURL>/evt/CmnIfCfg</eventSubURL><SCPDURL>/WANCfg.xml</SCPDURL></service></serviceList><deviceList><device><deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType><friendlyName>WANConnectionDevice</friendlyName><manufacturer>ARRIS</manufacturer><manufacturerURL>http://www.arrisi.com/</manufacturerURL><modelDescription>Residential Gateway</modelDescription><modelName>TG2492LG-85</modelName><modelNumber>20180122</modelNumber><modelURL>http://www.arrisi.com/</modelURL><serialNumber>AA1P80581207</serialNumber><UDN>uuid:30353831-3230-3700-0000-48d34396e685</UDN><UPC>TG2492LG-85</UPC><serviceList><service><serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType><serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId><controlURL>/ctl/IPConn</controlURL><eventSubURL>/evt/IPConn</eventSubURL><SCPDURL>/WANIPCn.xml</SCPDURL></service></serviceList></device></deviceList></device></deviceList><presentationURL>http://192.168.0.1/</presentationURL></device></root>', 477, 478, 'invalid continuation byte')>
Traceback (most recent call last):
  File "site-packages\aioupnp\gateway.py", line 177, in _discover_gateway
  File "site-packages\aioupnp\gateway.py", line 214, in discover_commands
  File "site-packages\aioupnp\protocols\scpd.py", line 114, in scpd_get
  File "site-packages\aioupnp\serialization\scpd.py", line 45, in deserialize_scpd_get_response
```

3) 
```future: <Task finished coro=<Gateway._discover_gateway() done, defined at site-packages\aioupnp\gateway.py:157> exception=UPnPError('M-SEARCH for 192.168.1.128:1900 timed out')>
Traceback (most recent call last):
  File "site-packages\aioupnp\gateway.py", line 169, in _discover_gateway
  File "site-packages\aioupnp\protocols\ssdp.py", line 173, in fuzzy_m_search
  File "site-packages\aioupnp\protocols\ssdp.py", line 166, in _fuzzy_m_search
aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.128:1900 timed out
2019-01-03 19:39:43,329 ERROR    asyncio:1597: Task exception was never retrieved
future: <Task finished coro=<Gateway._discover_gateway() done, defined at site-packages\aioupnp\gateway.py:157> exception=UPnPError('M-SEARCH for 192.168.1.128:1900 timed out')>
Traceback (most recent call last):
  File "site-packages\aioupnp\gateway.py", line 169, in _discover_gateway
  File "site-packages\aioupnp\protocols\ssdp.py", line 173, in fuzzy_m_search
  File "site-packages\aioupnp\protocols\ssdp.py", line 166, in _fuzzy_m_search
aioupnp.fault.UPnPError: M-SEARCH for 192.168.1.128:1900 timed out
2019-01-03 19:45:00,492 ERROR    aioupnp.protocols.ssdp:81: failed to decode SSDP packet from 192.168.1.13:1900 (missing required field server): b'485454502f312e3120323030204f4b0d0a53543a2075706e703a726f6f746465766963650d0a55534e3a20757569643a32383638313531302d326232622d346265302d613531652d3339643830613830663262383a3a75706e703a726f6f746465766963650d0a4c6f636174696f6e3a20687474703a2f2f3139322e3136382e312e31333a353030302f706c7567696e2f646973636f766572792f646973636f766572792e786d6c0d0a43616368652d436f6e74726f6c3a206d61782d6167653d36300d0a0d0a'```

**Comment by hackrush01** [comment]
3. Is solved, 1 and 2 are split into 6 and 7 respectively.

Closing
