### ISSUE TITLE
Invalid continuation byte

### ISSUE THREAD

**Issue by hackrush01** [lbryio/aioupnp#7]
```
future: <Task finished coro=<Gateway._discover_gateway() done, defined at site-packages\aioupnp\gateway.py:157> exception=UnicodeDecodeError('utf-8', b'<?xml version="1.0"?>\r\n<root xmlns="urn:schemas-upnp-org:device-1-0"><specVersion><major>1</major><minor>0</minor></specVersion><device><deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType><friendlyName>ARRIS TG2492LG-85 Router</friendlyName><manufacturer>ARRIS</manufacturer><manufacturerURL>http://www.arrisi.com/</manufacturerURL><modelDescription>ARRIS TG2492LG-85 Router</modelDescription><modelName>ARRIS TG2492LG-85 Router</modelName><modelNumber>\xf0_\xf0</modelNumber><modelURL>http://www.arrisi.com/</modelURL><serialNumber>AA1P80581207</serialNumber><UDN>uuid:30353831-3230-3700-0000-48d34396e685</UDN><serviceList><service><serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType><serviceId>urn:upnp-org:serviceId:Layer3Forwarding1</serviceId><controlURL>/ctl/L3F</controlURL><eventSubURL>/evt/L3F</eventSubURL><SCPDURL>/L3F.xml</SCPDURL></service></serviceList><deviceList><device><deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType><friendlyName>WANDevice</friendlyName><manufacturer>ARRIS</manufacturer><manufacturerURL>http://www.arrisi.com/</manufacturerURL><modelDescription>WANDevice</modelDescription><modelName>WANDevice</modelName><modelNumber>20180122</modelNumber><modelURL>http://www.arrisi.com/</modelURL><serialNumber>AA1P80581207</serialNumber><UDN>uuid:30353831-3230-3700-0000-48d34396e685</UDN><UPC>TG2492LG-85</UPC><serviceList><service><serviceType>urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1</serviceType><serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId><controlURL>/ctl/CmnIfCfg</controlURL><eventSubURL>/evt/CmnIfCfg</eventSubURL><SCPDURL>/WANCfg.xml</SCPDURL></service></serviceList><deviceList><device><deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType><friendlyName>WANConnectionDevice</friendlyName><manufacturer>ARRIS</manufacturer><manufacturerURL>http://www.arrisi.com/</manufacturerURL><modelDescription>Residential Gateway</modelDescription><modelName>TG2492LG-85</modelName><modelNumber>20180122</modelNumber><modelURL>http://www.arrisi.com/</modelURL><serialNumber>AA1P80581207</serialNumber><UDN>uuid:30353831-3230-3700-0000-48d34396e685</UDN><UPC>TG2492LG-85</UPC><serviceList><service><serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType><serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId><controlURL>/ctl/IPConn</controlURL><eventSubURL>/evt/IPConn</eventSubURL><SCPDURL>/WANIPCn.xml</SCPDURL></service></serviceList></device></deviceList></device></deviceList><presentationURL>http://192.168.0.1/</presentationURL></device></root>', 477, 478, 'invalid continuation byte')>
Traceback (most recent call last):
  File "site-packages\aioupnp\gateway.py", line 177, in _discover_gateway
  File "site-packages\aioupnp\gateway.py", line 214, in discover_commands
  File "site-packages\aioupnp\protocols\scpd.py", line 114, in scpd_get
  File "site-packages\aioupnp\serialization\scpd.py", line 45, in deserialize_scpd_get_response
```

**Comment by jackrobison** [comment]
This device has a modelNum of `ð_ð`
